imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@GeoBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType

        default_connection: biblio
        connections:
            biblio:
                driver:   pdo_mysql
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
            geo:
                driver:   pdo_mysql
                host:     '%database_host2%'
                port:     '%database_port2%'
                dbname:   '%database_name2%'
                user:     '%database_user2%'
                password: '%database_password2%'
                charset:  UTF8


    # Pour travailler sur 2 bases de données, on doit créér 2 ENTITY MANAGERS
    #
    # Attention! Pour les relations bilatérales, les utilisateurs de chacune de ces bases doivent
    # pouvoir faire des requêtes SELECT sur l'autre BASE
    #
    # GRANT SELECT ON `BIBLIO`.* TO 'GEO'@'%';
    # GRANT SELECT ON `GEO`.* TO 'BIBLIO'@'%';
    #
    orm:
        default_entity_manager: biblio
        entity_managers:
            biblio:
                connection: biblio
                mappings:
                    AppBundle: ~
                    GeoBundle: ~
            geo:
                connection: geo
                mappings:
                    GeoBundle: ~
                    AppBundle: ~
                dql:
                    numeric_functions:
                        # for mysql
                        area:                   CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Area
                        asbinary:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\AsBinary
                        astext:                 CrEOF\Spatial\ORM\Query\AST\Functions\MySql\AsText
                        buffer:                 CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Buffer
                        centroid:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Centroid
                        contains:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Contains
                        crosses:                CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Crosses
                        dimension:              CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Dimension
                        distance:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Distance
                        disjoint:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Disjoint
                        distancefrommultyLine:  CrEOF\Spatial\ORM\Query\AST\Functions\MySql\DistanceFromMultyLine
                        endpoint:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\EndPoint
                        envelope:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Envelope
                        equals:                 CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Equals
                        exteriorring:           CrEOF\Spatial\ORM\Query\AST\Functions\MySql\ExteriorRing
                        geodistpt:              CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeodistPt
                        geometrytype:           CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeometryType
                        geomfromtext:           CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GeomFromText
                        glength:                CrEOF\Spatial\ORM\Query\AST\Functions\MySql\GLength
                        interiorringn:          CrEOF\Spatial\ORM\Query\AST\Functions\MySql\InteriorRingN
                        intersects:             CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Intersects
                        isclosed:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\IsClosed
                        isempty:                CrEOF\Spatial\ORM\Query\AST\Functions\MySql\IsEmpty
                        issimple:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\IsSimple
                        linestringfromwkb:      CrEOF\Spatial\ORM\Query\AST\Functions\MySql\LineStringFromWKB
                        linestring:             CrEOF\Spatial\ORM\Query\AST\Functions\MySql\LineString
                        mbrcontains:            CrEOF\Spatial\ORM\Query\AST\Functions\MySql\MBRContains
                        mbrdisjoint:            CrEOF\Spatial\ORM\Query\AST\Functions\MySql\MBRDisjoint
                        mbrequal:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\MBREqual
                        mbrintersects:          CrEOF\Spatial\ORM\Query\AST\Functions\MySql\MBRIntersects
                        mbroverlaps:            CrEOF\Spatial\ORM\Query\AST\Functions\MySql\MBROverlaps
                        mbrtouches:             CrEOF\Spatial\ORM\Query\AST\Functions\MySql\MBRTouches
                        mbrwithin:              CrEOF\Spatial\ORM\Query\AST\Functions\MySql\MBRWithin
                        numinteriorrings:       CrEOF\Spatial\ORM\Query\AST\Functions\MySql\NumInteriorRings
                        numpoints:              CrEOF\Spatial\ORM\Query\AST\Functions\MySql\NumPoints
                        overlaps:               CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Overlaps
                        pointfromwkb:           CrEOF\Spatial\ORM\Query\AST\Functions\MySql\PointFromWKB
                        pointn:                 CrEOF\Spatial\ORM\Query\AST\Functions\MySql\PointN
                        point:                  CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Point
                        srid:                   CrEOF\Spatial\ORM\Query\AST\Functions\MySql\SRID
                        startpoint:             CrEOF\Spatial\ORM\Query\AST\Functions\MySql\StartPoint
                        st_buffer:              CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STBuffer
                        st_contains:            CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STContains
                        st_crosses:             CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STCrosses
                        st_disjoint:            CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STDisjoint
                        st_equals:              CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STEquals
                        st_intersects:          CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STIntersects
                        st_overlaps:            CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STOverlaps
                        st_touches:             CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STTouches
                        st_within:              CrEOF\Spatial\ORM\Query\AST\Functions\MySql\STWithin
                        touches:                CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Touches
                        within:                 CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Within
                        x:                      CrEOF\Spatial\ORM\Query\AST\Functions\MySql\X
                        y:                      CrEOF\Spatial\ORM\Query\AST\Functions\MySql\Y


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    auth_mode: "%mailer_auth_mode%"
    port:      "%mailer_port%"

# Fos USer Bundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User