geo:
    resource: "@GeoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# Fos User Routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"