app_auteur:
    resource: "@AppBundle/Controller/AuteurController.php"
    type:     annotation

geo:
    resource: "@GeoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
